version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - LOG_LEVEL=info
      - PATH=/app/node_modules/.bin:$PATH
      - npm_config_loglevel=verbose
    command: npm test

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PATH=/app/node_modules/.bin:$PATH
      - npm_config_loglevel=verbose
    command: npm run start:dev

  docs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run docs

volumes:
  node_modules:
