version: '3.8'
services:
  test:
    image: node:20-slim
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=test
      - CI=true
    command: bash -c "npm install && npm test"
